-- MySQL Script generated by MySQL Workbench
-- Sat Sep 30 18:12:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto_db` ;

-- -----------------------------------------------------
-- Schema proyecto_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_db` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_db` ;

-- -----------------------------------------------------
-- Table `proyecto_db`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`provincia` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`provincia` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  UNIQUE INDEX `id_provincia_UNIQUE` (`id_provincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`localidad` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`direccion` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `calle_nro` VARCHAR(100) NOT NULL,
  `provincia_id_provincia` INT NOT NULL,
  `localidad_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  UNIQUE INDEX `id_direccion_UNIQUE` (`id_direccion` ASC) VISIBLE,
  INDEX `fk_direccion_provincia1_idx` (`provincia_id_provincia` ASC) VISIBLE,
  INDEX `fk_direccion_localidad1_idx` (`localidad_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_provincia1`
    FOREIGN KEY (`provincia_id_provincia`)
    REFERENCES `proyecto_db`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `proyecto_db`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`cliente` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`cliente` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `tipo_usuario` TINYINT ZEROFILL NOT NULL COMMENT '0 for user\n1 for admin',
  `email` VARCHAR(60) NOT NULL,
  `dni` VARCHAR(8) NULL,
  `fecha_nac` DATE NULL,
  `telefono` VARCHAR(12) NULL,
  `direccion_id_direccion` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_modificacion` DATE NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_cliente_direccion1_idx` (`direccion_id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_direccion1`
    FOREIGN KEY (`direccion_id_direccion`)
    REFERENCES `proyecto_db`.`direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`autor` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id_autor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`idioma` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`idioma` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_idioma`),
  UNIQUE INDEX `id_idioma_UNIQUE` (`id_idioma` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`formato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`formato` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`formato` (
  `id_formato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_formato`),
  UNIQUE INDEX `id_formato_UNIQUE` (`id_formato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`editorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`editorial` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`editorial` (
  `id_editorial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_editorial`),
  UNIQUE INDEX `id_editorial_UNIQUE` (`id_editorial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`categoria` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`libro` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `comentarios` VARCHAR(1000) NULL,
  `precio` FLOAT NOT NULL,
  `autor_id_autor` INT NOT NULL,
  `idioma_id_idioma` INT NOT NULL,
  `formato_id_formato` INT UNSIGNED NOT NULL,
  `editorial_id_editorial` INT NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `id_libro_UNIQUE` (`id_libro` ASC) VISIBLE,
  INDEX `fk_libro_autor1_idx` (`autor_id_autor` ASC) VISIBLE,
  INDEX `fk_libro_idioma1_idx` (`idioma_id_idioma` ASC) VISIBLE,
  INDEX `fk_libro_formato1_idx` (`formato_id_formato` ASC) VISIBLE,
  INDEX `fk_libro_editorial1_idx` (`editorial_id_editorial` ASC) VISIBLE,
  INDEX `fk_libro_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `proyecto_db`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_idioma1`
    FOREIGN KEY (`idioma_id_idioma`)
    REFERENCES `proyecto_db`.`idioma` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_formato1`
    FOREIGN KEY (`formato_id_formato`)
    REFERENCES `proyecto_db`.`formato` (`id_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_editorial1`
    FOREIGN KEY (`editorial_id_editorial`)
    REFERENCES `proyecto_db`.`editorial` (`id_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `proyecto_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`wishlist` (
  `id_wishlist` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` VARCHAR(45) NULL,
  `cliente_id_usuario` INT NOT NULL,
  `fecha_modificacion` DATE NULL,
  PRIMARY KEY (`id_wishlist`),
  UNIQUE INDEX `id_carrito_UNIQUE` (`id_wishlist` ASC) VISIBLE,
  INDEX `fk_carrito_cliente1_idx` (`cliente_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente1`
    FOREIGN KEY (`cliente_id_usuario`)
    REFERENCES `proyecto_db`.`cliente` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`libro_has_detalles_orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`libro_has_detalles_orden` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`libro_has_detalles_orden` (
  `libro_id_libro` INT NOT NULL,
  `detalles_orden_id_orden` INT NOT NULL,
  PRIMARY KEY (`libro_id_libro`, `detalles_orden_id_orden`),
  INDEX `fk_libro_has_detalles_orden_libro1_idx` (`libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_detalles_orden_libro1`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `proyecto_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`elementos_wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto_db`.`elementos_wishlist` ;

CREATE TABLE IF NOT EXISTS `proyecto_db`.`elementos_wishlist` (
  `id_elementos_wishlist` INT NOT NULL AUTO_INCREMENT,
  `wishlist_id_wishlist` INT NOT NULL,
  `libro_id_libro` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_elementos_wishlist`),
  INDEX `fk_carrito_has_libro_libro1_idx` (`libro_id_libro` ASC) VISIBLE,
  INDEX `fk_carrito_has_libro_carrito1_idx` (`wishlist_id_wishlist` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_has_libro_carrito1`
    FOREIGN KEY (`wishlist_id_wishlist`)
    REFERENCES `proyecto_db`.`wishlist` (`id_wishlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_libro_libro1`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `proyecto_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
