-- MySQL Script generated by MySQL Workbench
-- Sun May  7 20:11:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto_db` ;

-- -----------------------------------------------------
-- Schema proyecto_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_db` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_db` ;

-- -----------------------------------------------------
-- Table `proyecto_db`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`provincia` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  UNIQUE INDEX `id_provincia_UNIQUE` (`id_provincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `calle_nro` VARCHAR(100) NOT NULL,
  `provincia_id_provincia` INT NOT NULL,
  `localidad_id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  UNIQUE INDEX `id_direccion_UNIQUE` (`id_direccion` ASC) VISIBLE,
  INDEX `fk_direccion_provincia1_idx` (`provincia_id_provincia` ASC) VISIBLE,
  INDEX `fk_direccion_localidad1_idx` (`localidad_id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_provincia1`
    FOREIGN KEY (`provincia_id_provincia`)
    REFERENCES `proyecto_db`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_localidad1`
    FOREIGN KEY (`localidad_id_localidad`)
    REFERENCES `proyecto_db`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`cliente` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `tipo_usuario` TINYINT ZEROFILL NOT NULL COMMENT '0 for user\n1 for admin',
  `email` VARCHAR(60) NOT NULL,
  `dni` VARCHAR(8) NULL,
  `fecha_nac` DATE NULL,
  `telefono` VARCHAR(12) NULL,
  `direccion_id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_cliente_direccion1_idx` (`direccion_id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_direccion1`
    FOREIGN KEY (`direccion_id_direccion`)
    REFERENCES `proyecto_db`.`direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id_autor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`idioma` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_idioma`),
  UNIQUE INDEX `id_idioma_UNIQUE` (`id_idioma` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`formato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`formato` (
  `id_formato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_formato`),
  UNIQUE INDEX `id_formato_UNIQUE` (`id_formato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`editorial` (
  `id_editorial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_editorial`),
  UNIQUE INDEX `id_editorial_UNIQUE` (`id_editorial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NULL,
  `paginas` INT NULL,
  `peso` INT NULL,
  `edicion` YEAR NULL,
  `resenia` VARCHAR(1000) NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  `autor_id_autor` INT NOT NULL,
  `idioma_id_idioma` INT NOT NULL,
  `formato_id_formato` INT UNSIGNED NOT NULL,
  `editorial_id_editorial` INT NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `id_libro_UNIQUE` (`id_libro` ASC) VISIBLE,
  INDEX `fk_libro_autor1_idx` (`autor_id_autor` ASC) VISIBLE,
  INDEX `fk_libro_idioma1_idx` (`idioma_id_idioma` ASC) VISIBLE,
  INDEX `fk_libro_formato1_idx` (`formato_id_formato` ASC) VISIBLE,
  INDEX `fk_libro_editorial1_idx` (`editorial_id_editorial` ASC) VISIBLE,
  INDEX `fk_libro_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_id_autor`)
    REFERENCES `proyecto_db`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_idioma1`
    FOREIGN KEY (`idioma_id_idioma`)
    REFERENCES `proyecto_db`.`idioma` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_formato1`
    FOREIGN KEY (`formato_id_formato`)
    REFERENCES `proyecto_db`.`formato` (`id_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_editorial1`
    FOREIGN KEY (`editorial_id_editorial`)
    REFERENCES `proyecto_db`.`editorial` (`id_editorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `proyecto_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`carrito` (
  `id_carrito` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` VARCHAR(45) NULL,
  `cliente_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_carrito`),
  UNIQUE INDEX `id_carrito_UNIQUE` (`id_carrito` ASC) VISIBLE,
  INDEX `fk_carrito_cliente1_idx` (`cliente_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente1`
    FOREIGN KEY (`cliente_id_usuario`)
    REFERENCES `proyecto_db`.`cliente` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`libro_has_detalles_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`libro_has_detalles_orden` (
  `libro_id_libro` INT NOT NULL,
  `detalles_orden_id_orden` INT NOT NULL,
  PRIMARY KEY (`libro_id_libro`, `detalles_orden_id_orden`),
  INDEX `fk_libro_has_detalles_orden_libro1_idx` (`libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_detalles_orden_libro1`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `proyecto_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`elementos_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`elementos_carrito` (
  `id_elementos_carrito` INT NOT NULL AUTO_INCREMENT,
  `carrito_id_carrito` INT NOT NULL,
  `libro_id_libro` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`id_elementos_carrito`),
  INDEX `fk_carrito_has_libro_libro1_idx` (`libro_id_libro` ASC) VISIBLE,
  INDEX `fk_carrito_has_libro_carrito1_idx` (`carrito_id_carrito` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_has_libro_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `proyecto_db`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_libro_libro1`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `proyecto_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`estado` (
  `id_estado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL COMMENT '1. aceptado\n2. declinado\n3. pendiente',
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`orden` (
  `id_orden` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NULL,
  `ordencol` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `cliente_id_usuario` INT NOT NULL,
  `estado_id_estado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_orden`),
  INDEX `fk_orden_cliente1_idx` (`cliente_id_usuario` ASC) VISIBLE,
  INDEX `fk_orden_estado1_idx` (`estado_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_orden_cliente1`
    FOREIGN KEY (`cliente_id_usuario`)
    REFERENCES `proyecto_db`.`cliente` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `proyecto_db`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`seguimiento` (
  `id_seguimiento` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL COMMENT '1. en_proceso\n2. en_camino\n3. entregado\n4. devolucion',
  PRIMARY KEY (`id_seguimiento`),
  UNIQUE INDEX `id_seguimiento_UNIQUE` (`id_seguimiento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `nro_seguimiento` VARCHAR(45) NULL,
  `cliente_id_usuario` INT NOT NULL,
  `fecha` DATE NULL,
  `orden_id_orden` INT UNSIGNED NOT NULL,
  `seguimiento_id_seguimiento` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `nro_seguimiento_UNIQUE` (`nro_seguimiento` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_id_usuario` ASC) VISIBLE,
  INDEX `fk_pedido_orden1_idx` (`orden_id_orden` ASC) VISIBLE,
  INDEX `fk_pedido_seguimiento1_idx` (`seguimiento_id_seguimiento` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id_usuario`)
    REFERENCES `proyecto_db`.`cliente` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_orden1`
    FOREIGN KEY (`orden_id_orden`)
    REFERENCES `proyecto_db`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_seguimiento1`
    FOREIGN KEY (`seguimiento_id_seguimiento`)
    REFERENCES `proyecto_db`.`seguimiento` (`id_seguimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  INDEX `fk_detalle_pedido_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `proyecto_db`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`detalle_pedido_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`detalle_pedido_libro` (
  `detalle_pedido_id_detalle_pedido` INT NOT NULL,
  `libro_id_libro` INT NOT NULL,
  PRIMARY KEY (`detalle_pedido_id_detalle_pedido`, `libro_id_libro`),
  INDEX `fk_detalle_pedido_has_libro_libro1_idx` (`libro_id_libro` ASC) VISIBLE,
  INDEX `fk_detalle_pedido_has_libro_detalle_pedido1_idx` (`detalle_pedido_id_detalle_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido_has_libro_detalle_pedido1`
    FOREIGN KEY (`detalle_pedido_id_detalle_pedido`)
    REFERENCES `proyecto_db`.`detalle_pedido` (`id_detalle_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_has_libro_libro1`
    FOREIGN KEY (`libro_id_libro`)
    REFERENCES `proyecto_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_db`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_db`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` FLOAT NOT NULL,
  `info_adic` VARCHAR(45) NOT NULL COMMENT 'almacena los 4 ultimos digitos del medio de pago',
  `orden_id_orden` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pago`),
  UNIQUE INDEX `id_pago_UNIQUE` (`id_pago` ASC) VISIBLE,
  INDEX `fk_pago_orden1_idx` (`orden_id_orden` ASC) VISIBLE,
  CONSTRAINT `fk_pago_orden1`
    FOREIGN KEY (`orden_id_orden`)
    REFERENCES `proyecto_db`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
