# Generated by Django 4.2.1 on 2023-06-19 16:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=150, unique=True)),
                (
                    "dni",
                    models.CharField(
                        help_text="Maximo 8 caracteres", max_length=8, null=True
                    ),
                ),
                ("fecha_nac", models.DateField(null=True)),
                (
                    "telefono",
                    models.CharField(
                        help_text="Maximo 12 caracteres", max_length=12, null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id_autor",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Maximo 50 caracteres", max_length=50),
                ),
                (
                    "apellido",
                    models.CharField(help_text="Maximo 50 caracteres", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "db_table": "autor",
            },
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id_carrito",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="The field is only automatically updated when calling Model.save()",
                    ),
                ),
            ],
            options={
                "verbose_name": "Id del Carrito",
                "verbose_name_plural": "Ids de los Carritos",
                "db_table": "carrito",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id_categoria",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Maximo 50 caracteres", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id_editorial",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Maximo 50 caracteres", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Editorial",
                "verbose_name_plural": "Editoriales",
                "db_table": "editorial",
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id_estado",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PP", "Pagado"),
                            ("RR", "Rechazado"),
                            ("AA", "Esperando Autorizacion"),
                        ],
                        default="AA",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "estado",
            },
        ),
        migrations.CreateModel(
            name="Formato",
            fields=[
                (
                    "id_formato",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Maximo 50 caracteres", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Formato",
                "verbose_name_plural": "Formatos",
                "db_table": "formato",
            },
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "id_idioma",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("EN", "Ingles"),
                            ("ES", "Espaniol"),
                            ("FR", "Frances"),
                            ("IT", "Italiano"),
                            ("DE", "Aleman"),
                            ("ZH", "Chino"),
                            ("JA", "Japones"),
                            ("PT", "Portugues"),
                            ("RU", "Ruso"),
                            ("AR", "Arabe"),
                        ],
                        default="ES",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Idioma",
                "verbose_name_plural": "Idiomas",
                "db_table": "idioma",
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id_localidad",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Maximo 100 caracteres", max_length=100),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        help_text="Codigo postal de 8 caracteres", max_length=8
                    ),
                ),
            ],
            options={
                "verbose_name": "Nombre de Localidad",
                "verbose_name_plural": "Nombres de Localidades",
                "db_table": "localidad",
            },
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id_orden",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The field is only automatically updated when calling Model.save()",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, max_length=99999
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Ordenes",
                "db_table": "orden",
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id_provincia",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("BA", "Buenos Aires"),
                            ("CT", "Catamarca"),
                            ("CH", "Chaco"),
                            ("CB", "Chubut"),
                            ("CD", "Cordoba"),
                            ("CR", "Corrientes"),
                            ("ER", "Entre Rios"),
                            ("FO", "Formosa"),
                            ("JY", "Jujuy"),
                            ("LP", "La Pampa"),
                            ("LR", "La Rioja"),
                            ("MZ", "Mendoza"),
                            ("MN", "Misiones"),
                            ("NQ", "Neuquen"),
                            ("RN", "Rio Negro"),
                            ("SA", "Salta"),
                            ("SJ", "San Juan"),
                            ("SL", "San Luis"),
                            ("SC", "Santa Cruz"),
                            ("SF", "Santa Fe"),
                            ("SE", "Santiago Del Estero"),
                            ("TF", "Tierra Del Fuego"),
                            ("TM", "Tucuman"),
                        ],
                        default="BA",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nombre de Provincia",
                "verbose_name_plural": "Nombres de Provincias",
                "db_table": "provincia",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id_pedido",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "seguimiento",
                    models.CharField(
                        choices=[
                            ("CC", "En Camino"),
                            ("AA", "Armando Pedido"),
                            ("EE", "Entregado"),
                            ("DV", "Devolucion"),
                        ],
                        default="AA",
                        max_length=2,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The field is only automatically updated when calling Model.save()",
                    ),
                ),
                (
                    "nro_tracking",
                    models.CharField(help_text="Maximo 40 caracteres", max_length=40),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": "pedido",
            },
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id_pagos",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The field is only automatically updated when calling Model.save()",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "dni",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "email",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "tarjeta",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "titular",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "vencimiento",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagos",
                "verbose_name_plural": "Datos generales de Pagos",
                "db_table": "pagos",
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id_pago",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The field is only automatically updated when calling Model.save()",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, max_length=99999
                    ),
                ),
                (
                    "info_adicional",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "id_orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pago",
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id_libro",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="Maximo 17 caracteres incluido guiones",
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                (
                    "subtitulo",
                    models.CharField(help_text="Maximo 200 caracteres", max_length=200),
                ),
                ("paginas", models.PositiveSmallIntegerField()),
                ("peso", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "edicion",
                    models.CharField(help_text="Anio de edicion", max_length=4),
                ),
                (
                    "resenia",
                    models.CharField(
                        help_text="Maximo 1000 caracteres", max_length=1000
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=7)),
                ("stock", models.PositiveSmallIntegerField()),
                (
                    "img_url",
                    models.URLField(
                        default="https://unrulyguides.com/wp-content/uploads/2011/12/generic-cover.jpg"
                    ),
                ),
                (
                    "id_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.autor",
                    ),
                ),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.categoria",
                    ),
                ),
                (
                    "id_editorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.editorial",
                    ),
                ),
                (
                    "id_formato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.formato",
                    ),
                ),
                (
                    "id_idioma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.idioma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "db_table": "libro",
            },
        ),
        migrations.CreateModel(
            name="ElementosCarrito",
            fields=[
                (
                    "id_elementos_carrito",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField()),
                (
                    "id_carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.carrito",
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento del Carrito",
                "verbose_name_plural": "Elementos de los Carritos",
                "db_table": "elementos_carrito",
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id_direccion",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "calle_nro",
                    models.CharField(
                        help_text="Calle, numero, piso, departamento", max_length=100
                    ),
                ),
                (
                    "id_localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.localidad",
                    ),
                ),
                (
                    "id_provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Direccion",
                "verbose_name_plural": "Detalles de Direcciones",
                "db_table": "direccion",
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id_detalle_pedido",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField()),
                (
                    "id_libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.libro",
                    ),
                ),
                (
                    "id_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreriavirtual.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle del Pedido",
                "verbose_name_plural": "Detalles de los Pedidos",
                "db_table": "detalle_pedido",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_carrito",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customuser",
                to="libreriavirtual.carrito",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="id_direccion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="libreriavirtual.direccion",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
